[package]
name = "imap-filter"
version = "0.1.0"
authors = ["Fred Mitchell <fred.mitchell@gmx.de>"]
edition = "2018"

[dependencies]
async-imap = "0.2.0"
clap-nested = "0.3.1"
qt_core = "0.4.1"

[workspace]
members = [
    "if-dsl",
]
