[package]
name = "if-dsl"
version = "0.1.0"
authors = ["Fred Mitchell <fred.mitchell@gmx.de>"]
edition = "2018"

[dependencies]
cfgrammar = "0.6.1"
lrpar = "0.6.1"
lrlex = "0.6.1"

[build-dependencies]
cfgrammar = "0.6.1"
lrpar = "0.6.1"
lrlex = "0.6.1"